#line chart on gold and coffee trade 
library(tidyverse)
library(dplyr)
coffee <- read_csv("coffee-gold.csv")
# basic line plot 
plot <- ggplot(data= coffee, aes(x = Year)) + geom_line(aes(y = Coffee), size = 0.9, color = "#2ca25f") +geom_line(aes(y = Gold, ), size=0.9, color="maroon")

# labels customisation 
plot <- plot + scale_x_continuous(limits = c(1999, 2021.5), expand = c(0,0), breaks = c(2000, 2005, 2010, 2015, 2020), labels = c("2000", "05", "10", "15", "2020")) + scale_y_continuous(limits = c(-10, 2000), breaks = seq(400, 1800, by = 400), expand = c(0,0), position = "left", labels = (labels=scales::dollar_format()))

# clean

plot <- plot + theme(panel.background = element_rect(fill = "white"), panel.grid = element_blank(), panel.grid.major.y = element_line(color = "#A8BAC4", size = 0.3), axis.line.x.bottom = element_line(color = "black"),  axis.ticks.length.y = unit(0, "mm"), axis.ticks.length.x = unit(2, "mm"), axis.text.x = element_text(family = "Arial", size = 10), axis.text.y = element_text(family = "Arial", size = 10, hjust = 2, vjust = -0.3)) + theme(axis.title.x = element_blank()) + theme(axis.title.y = element_blank())

# Annotate 
# curvature gold
plot <- plot + annotate(geom = "text", x = 2014, y = 1400, label = "Gold", size = 6, family = "Arial", lineheight = 0.2) + annotate(geom = "curve", x = 2019.9, y = 1760, xend = 2015, yend = 1410, curvature = 0.4, colour = "grey", size=0.4, alpha=0.9, arrow = arrow(length = unit(0.2, "cm"), ends = "first"))

#million
plot <- plot + annotate(geom = "text", x = 1999.7, y = 1630, label = "(mn)", size = 3, family = "Arial", lineheight = 0.2)

# coffee annotate 

plot <- plot + annotate( geom = "text", x = 2005, y = 600, label = "Coffee", size = 6, family = "Arial", lineheight = 0.2) + annotate(geom = "curve", x = 2013, y = 430, xend = 2006.3, yend = 600, curvature = 0.2, colour = "grey", size=0.4, alpha=0.9, arrow = arrow(length = unit(0.2, "cm"), ends = "first"))

#margins
plot <- plot + theme( plot.margin = margin(0.009, 0.009, 0.009, 0.002, "npc"))


plot <- plot + labs(title = "Eyes on coffee", subtitle = "With the end of gold export boom, coffee will be Uganda's \n top export earners and there is a fight over who should control it", caption = "Source: Bank of Uganda \n The Africa Report Magazine") + theme(plot.title = element_text(family = "Arial", face = "bold", size = 20, vjust = -2), plot.subtitle = element_text(family = "Arial", size = 16, vjust = -2), plot.caption = element_text(size = 12, hjust = c(0, 0)))

plot
# save
ggsave("coffee-final27.png", plot, units = "cm", width = 20, height =14, dpi = 300)
